// Package client includes types and methods to access the Bulk Stock Quotes endpoint.
// Retrieve real-time quotes for multiple stocks symbols in a single request or even get a full market snapshot with a quote for all symbols.
//
// # Making Requests
//
// Utilize [BulkStockQuotesRequest] to make requests to the endpoint through one of the three supported execution methods:
//
//	| Method     | Execution     | Return Type                | Description                                                                                               |
//	|------------|---------------|----------------------------|-----------------------------------------------------------------------------------------------------------|
//	| **Get**    | Direct        | `[]StockQuote`             | Directly returns a slice of `[]StockQuote`, facilitating individual access to each stock quote.           |
//	| **Packed** | Intermediate  | `StockQuotesResponse`      | Returns a packed `StockQuotesResponse` object. Must be unpacked to access the `[]StockQuote` slice.       |
//	| **Raw**    | Low-level     | `resty.Response`           | Offers the raw `resty.Response` for utmost flexibility. Direct access to raw JSON or `*http.Response`.    |
package client

import (
	"fmt"

	"github.com/MarketDataApp/sdk-go/helpers/parameters"
	"github.com/MarketDataApp/sdk-go/models"
)

// BulkStockQuotesRequest represents a request to the [v1/stocks/bulkquotes/] endpoint.
// It encapsulates parameters for symbol and fifty-two-week data to be used in the request.
// This struct provides methods such as Symbol() and FiftyTwoWeek() to set these parameters respectively.
//
// # Generated By
//
//   - BulkStockQuotes(client ...*MarketDataClient) *BulkStockQuotesRequest: BulkStockQuotes creates a new *BulkStockQuotesRequest and returns a pointer to the request allowing for method chaining.
//
// # Setter Methods
//
//   - Symbol(string) *BulkStockQuotesRequest: Sets the symbol parameter for the request.
//   - FiftyTwoWeek(bool) *BulkStockQuotesRequest: Sets the fifty-two-week data parameter for the request.
//
// # Execution Methods
//
// These methods are used to send the request in different formats or retrieve the data.
// They handle the actual communication with the API endpoint.
//
//   - Raw() (*resty.Response, error): Sends the request as is and returns the raw HTTP response.
//   - Packed() (*StockQuotesResponse, error): Returns a struct that contains equal-length slices of primitives. This packed response mirrors Market Data's JSON response.
//   - Get() ([]Candle, error): Sends the request, unpacks the response, and returns the data in a user-friendly format.
//
// [v1/stocks/bulkquotes/]: https://www.marketdata.app/docs/api/stocks/bulkquotes
type BulkStockQuotesRequest struct {
	*baseRequest
	bulkStockParams *parameters.BulkStockParams
}

// Symbols sets the symbols parameter for the BulkStockQuotesRequest.
// This method is used to specify multiple stock symbols for which candle data is requested.
//
// # Parameters
//
//   - []string: A slice of []string representing the stock symbols to be set.
//
// # Returns
//
//   - *BulkStockQuotesRequest: This method returns a pointer to the BulkStockQuotesRequest instance it was called on. This allows for method chaining.
func (bs *BulkStockQuotesRequest) Symbols(q []string) *BulkStockQuotesRequest {
	if bs == nil {
		return nil
	}
	err := bs.bulkStockParams.SetSymbols(q)
	if err != nil {
		bs.Error = err
	}
	return bs
}

// Snapshot sets the snapshot parameter for the BulkStockQuotesRequest. This method is used to enable
// or disable the snapshot feature in the request and will result in all available tickers being returned in the response.
//
// # Parameters
//
//   - bool: A boolean value representing whether to enable or disable the snapshot feature.
//
// # Returns
//
//   - *BulkStockQuotesRequest: This method returns a pointer to the *BulkStockQuotesRequest instance it was called on. This allows for method chaining.
func (bs *BulkStockQuotesRequest) Snapshot(q bool) *BulkStockQuotesRequest {
	if bs == nil {
		return nil
	}
	bs.bulkStockParams.SetSnapshot(q)
	return bs
}

// getParams packs the BulkStockQuotesRequest struct into a slice of interface{} and returns it.
func (bs *BulkStockQuotesRequest) getParams() ([]parameters.MarketDataParam, error) {
	if bs == nil {
		return nil, fmt.Errorf("BulkStockQuotesRequest is nil")
	}
	params := []parameters.MarketDataParam{bs.bulkStockParams}
	return params, nil
}

// Packed sends the BulkStockQuotesRequest and returns the StockQuotesResponse.
// An optional MarketDataClient can be passed to replace the client used in the request.
//
// # Parameters
//
//   - ...*MarketDataClient: A variadic parameter that can accept zero or one MarketDataClient pointer. If a client is provided, it replaces the current client for this request.
//
// # Returns
//
//   - *models.StockQuotesResponse: A pointer to the StockQuotesResponse obtained from the request.
//   - error: An error object that indicates a failure in sending the request.
func (bs *BulkStockQuotesRequest) Packed(optionalClients ...*MarketDataClient) (*models.StockQuotesResponse, error) {
	if bs == nil {
		return nil, fmt.Errorf("BulkStockQuotesRequest is nil")
	}

	// Replace the client if an optional client is provided
	if len(optionalClients) > 0 && optionalClients[0] != nil {
		bs.baseRequest.client = optionalClients[0]
	}

	var bsResp models.StockQuotesResponse
	_, err := bs.baseRequest.client.GetFromRequest(bs.baseRequest, &bsResp)
	if err != nil {
		return nil, err
	}

	return &bsResp, nil
}

// Get sends the BulkStockQuotesRequest, unpacks the StockQuotesResponse, and returns a slice of StockQuote.
// It returns an error if the request or unpacking fails.
// An optional MarketDataClient can be passed to replace the client used in the request.
//
// # Parameters
//
//   - ...*MarketDataClient: A variadic parameter that can accept zero or one MarketDataClient pointer. If a client is provided, it replaces the current client for this request.
//
// # Returns
//
//   - []models.StockQuote: A slice of StockQuote containing the unpacked quote data from the response.
//   - error: An error object that indicates a failure in sending the request or unpacking the response.
func (bs *BulkStockQuotesRequest) Get(optionalClients ...*MarketDataClient) ([]models.StockQuote, error) {
	if bs == nil {
		return nil, fmt.Errorf("BulkStockQuotesRequest is nil")
	}

	// Use the Packed method to make the request, passing along any optional client
	bsResp, err := bs.Packed(optionalClients...)
	if err != nil {
		return nil, err
	}

	// Unpack the data using the Unpack method in the response
	data, err := bsResp.Unpack()
	if err != nil {
		return nil, err
	}

	return data, nil
}

// BulkStockQuotes creates a new BulkStockQuotesRequest and associates it with the provided client.
// If no client is provided, it uses the default client. This function initializes the request
// with default parameters for symbol and fifty-two-week data, and sets the request path based on
// the predefined endpoints for stock quotes.
//
// # Parameters
//
//   - ...*MarketDataClient: A variadic parameter that can accept zero or one MarketDataClient pointer. If no client is provided, the default client is used.
//
// # Returns
//
//   - *BulkStockQuotesRequest: A pointer to the newly created BulkStockQuotesRequest with default parameters and associated client.
func BulkStockQuotes(client ...*MarketDataClient) *BulkStockQuotesRequest {
	baseReq := newBaseRequest(client...)
	baseReq.path = endpoints[1]["stocks"]["bulkquotes"]

	bs := &BulkStockQuotesRequest{
		baseRequest:     baseReq,
		bulkStockParams: &parameters.BulkStockParams{},
	}

	baseReq.child = bs

	return bs
}
